export interface ChemicalFormula {
  id: string;
  name: string;
  formula: string;
  type: 'Acid' | 'Base' | 'Salt' | 'Gas' | 'Organic' | 'Other';
  mnemonic: string;
  breakdown: string;
  trick: string;
}

export const FORMULA_DATABASE: ChemicalFormula[] = [
  // Acids
  {
    id: 'h2so4',
    name: 'Sulfuric Acid',
    formula: 'H₂SO₄',
    type: 'Acid',
    mnemonic: '"King of Chemicals"',
    breakdown: 'H₂ (Hydrogen) + SO₄ (Sulfate)',
    trick: 'Remember "H2-SO-4". Two hydrogens, one sulfur, four oxygens. It\'s the strongest common acid.',
  },
  {
    id: 'hcl',
    name: 'Hydrochloric Acid',
    formula: 'HCl',
    type: 'Acid',
    mnemonic: 'Hydrogen + Chlorine',
    breakdown: 'H⁺ (Valency 1) + Cl⁻ (Valency 1)',
    trick: 'The simplest strong acid. Just one H and one Cl. Found in stomach acid.',
  },
  {
    id: 'hno3',
    name: 'Nitric Acid',
    formula: 'HNO₃',
    type: 'Acid',
    mnemonic: 'Hydrogen + Nitrate',
    breakdown: 'H⁺ (Valency 1) + NO₃⁻ (Valency 1)',
    trick: 'Nitrate is NO3. Add an H for the acid. HNO3.',
  },
  {
    id: 'ch3cooh',
    name: 'Acetic Acid (Vinegar)',
    formula: 'CH₃COOH',
    type: 'Acid',
    mnemonic: 'CH3 + COOH (Carboxylic group)',
    breakdown: 'CH₃ (Methyl) + COOH (Acid group)',
    trick: 'It\'s an organic acid. The secret is the "COOH" at the end, which makes it an acid.',
  },
  {
    id: 'h2co3',
    name: 'Carbonic Acid',
    formula: 'H₂CO₃',
    type: 'Acid',
    mnemonic: 'Water + Carbon Dioxide',
    breakdown: 'H⁺ (Valency 1) + CO₃²⁻ (Valency 2)',
    trick: 'Carbonate is CO3. It has a valency of 2, so it needs 2 Hydrogens (cross-valency rule).',
  },

  // Bases
  {
    id: 'naoh',
    name: 'Sodium Hydroxide',
    formula: 'NaOH',
    type: 'Base',
    mnemonic: 'Na (Sodium) + OH (Hydroxide)',
    breakdown: 'Na⁺ (Valency 1) + OH⁻ (Valency 1)',
    trick: 'Strong base. Since both have valency 1, just stick them together: NaOH.',
  },
  {
    id: 'koh',
    name: 'Potassium Hydroxide',
    formula: 'KOH',
    type: 'Base',
    mnemonic: 'K (Potassium) + OH (Hydroxide)',
    breakdown: 'K⁺ (Valency 1) + OH⁻ (Valency 1)',
    trick: 'Same rule as NaOH. Potassium is K, hydroxide is OH.',
  },
  {
    id: 'caoh2',
    name: 'Calcium Hydroxide (Slaked Lime)',
    formula: 'Ca(OH)₂',
    type: 'Base',
    mnemonic: 'Ca (Calcium) + OH (Hydroxide)',
    breakdown: 'Ca²⁺ (Valency 2) + OH⁻ (Valency 1)',
    trick: 'Cross-valency rule: Calcium gives its 2 to OH, so we need parentheses: Ca(OH)₂.',
  },
  {
    id: 'nh4oh',
    name: 'Ammonium Hydroxide',
    formula: 'NH₄OH',
    type: 'Base',
    mnemonic: 'Ammonium + Hydroxide',
    breakdown: 'NH₄⁺ (Valency 1) + OH⁻ (Valency 1)',
    trick: 'Ammonium is a special positive ion (NH4). Stick it to OH to get a weak base.',
  },

  // Salts
  {
    id: 'nacl',
    name: 'Sodium Chloride (Table Salt)',
    formula: 'NaCl',
    type: 'Salt',
    mnemonic: 'Na (Sodium) + Cl (Chlorine)',
    breakdown: 'Na⁺ (Valency 1) + Cl⁻ (Valency 1)',
    trick: 'The most common salt. Valencies balance out perfectly 1:1.',
  },
  {
    id: 'caco3',
    name: 'Calcium Carbonate (Limestone)',
    formula: 'CaCO₃',
    type: 'Salt',
    mnemonic: 'Ca (Calcium) + CO3 (Carbonate)',
    breakdown: 'Ca²⁺ (Valency 2) + CO₃²⁻ (Valency 2)',
    trick: 'Since both have valency 2, they cancel out. Ca + CO3 = CaCO3.',
  },
  {
    id: 'nahco3',
    name: 'Sodium Bicarbonate (Baking Soda)',
    formula: 'NaHCO₃',
    type: 'Salt',
    mnemonic: 'Na + H + CO3',
    breakdown: 'Na⁺ + HCO₃⁻ (Bicarbonate)',
    trick: '"Bi" stands for Hydrogen here. Bicarbonate is HCO3. Add Sodium to get baking soda.',
  },
  {
    id: 'na2co3',
    name: 'Sodium Carbonate (Washing Soda)',
    formula: 'Na₂CO₃',
    type: 'Salt',
    mnemonic: 'Na (Sodium) + CO3 (Carbonate)',
    breakdown: 'Na⁺ (Valency 1) + CO₃²⁻ (Valency 2)',
    trick: 'Cross-valency: Carbonate gives its 2 to Sodium, so you need two Sodiums (Na₂).',
  },
  {
    id: 'cuso4',
    name: 'Copper Sulfate',
    formula: 'CuSO₄',
    type: 'Salt',
    mnemonic: 'Cu (Copper) + SO4 (Sulfate)',
    breakdown: 'Cu²⁺ (Valency 2) + SO₄²⁻ (Valency 2)',
    trick: 'Blue crystals! Both have valency 2, they cancel out. Just CuSO4.',
  },
  {
    id: 'caocl2',
    name: 'Bleaching Powder',
    formula: 'CaOCl₂',
    type: 'Salt',
    mnemonic: 'Calcium Oxychloride',
    breakdown: 'Ca²⁺ + O²⁻ + 2Cl⁻',
    trick: 'Remember it as Calcium Oxide with Chlorine attached. CaO + Cl2.',
  },
  {
    id: 'caso4_12h2o',
    name: 'Plaster of Paris',
    formula: 'CaSO₄·½H₂O',
    type: 'Salt',
    mnemonic: 'Calcium Sulfate Hemihydrate',
    breakdown: 'CaSO₄ + ½ H₂O (Water of crystallization)',
    trick: 'Hemihydrate means half a water molecule! Formed by heating Gypsum.',
  },
  {
    id: 'caso4_2h2o',
    name: 'Gypsum',
    formula: 'CaSO₄·2H₂O',
    type: 'Salt',
    mnemonic: 'Calcium Sulfate Dihydrate',
    breakdown: 'CaSO₄ + 2 H₂O',
    trick: '"Di" means two waters. Hardens when Plaster of Paris is mixed with water.',
  },
  {
    id: 'agcl',
    name: 'Silver Chloride',
    formula: 'AgCl',
    type: 'Salt',
    mnemonic: 'Ag (Silver) + Cl (Chlorine)',
    breakdown: 'Ag⁺ (Valency 1) + Cl⁻ (Valency 1)',
    trick: 'Used in black and white photography (photo-decomposition). Turns grey in sunlight.',
  },
  {
    id: 'pbno32',
    name: 'Lead Nitrate',
    formula: 'Pb(NO₃)₂',
    type: 'Salt',
    mnemonic: 'Pb (Lead) + NO3 (Nitrate)',
    breakdown: 'Pb²⁺ (Valency 2) + NO₃⁻ (Valency 1)',
    trick: 'Cross-valency: Lead gives its 2 to Nitrate, requiring parentheses: Pb(NO3)2.',
  },
  {
    id: 'kmno4',
    name: 'Potassium Permanganate',
    formula: 'KMnO₄',
    type: 'Salt',
    mnemonic: 'K + MnO4',
    breakdown: 'K⁺ (Valency 1) + MnO₄⁻ (Valency 1)',
    trick: 'A powerful purple oxidizing agent used in carbon chemistry.',
  },
  {
    id: 'feso4',
    name: 'Ferrous Sulfate',
    formula: 'FeSO₄',
    type: 'Salt',
    mnemonic: 'Fe (Iron II) + SO4 (Sulfate)',
    breakdown: 'Fe²⁺ (Valency 2) + SO₄²⁻ (Valency 2)',
    trick: 'Green crystals. Both valencies are 2, so they cancel out.',
  },
  {
    id: 'mgcl2',
    name: 'Magnesium Chloride',
    formula: 'MgCl₂',
    type: 'Salt',
    mnemonic: 'Mg + 2 Cl',
    breakdown: 'Mg²⁺ (Valency 2) + Cl⁻ (Valency 1)',
    trick: 'Cross-valency: Magnesium gives its 2 to Chlorine. Hence MgCl2.',
  },
  {
    id: 'al2o3',
    name: 'Aluminum Oxide',
    formula: 'Al₂O₃',
    type: 'Salt',
    mnemonic: 'Al (Aluminum) + O (Oxygen)',
    breakdown: 'Al³⁺ (Valency 3) + O²⁻ (Valency 2)',
    trick: 'Cross-valency: Aluminum gives 3 to Oxygen, Oxygen gives 2 to Aluminum ➔ Al₂O₃.',
  },
  {
    id: 'fe2o3',
    name: 'Iron(III) Oxide (Rust)',
    formula: 'Fe₂O₃',
    type: 'Salt',
    mnemonic: 'Fe (Iron III) + O (Oxygen)',
    breakdown: 'Fe³⁺ (Valency 3) + O²⁻ (Valency 2)',
    trick: 'Same as Aluminum Oxide! Iron gives its 3 to Oxygen, Oxygen gives its 2 to Iron.',
  },
  {
    id: 'cao',
    name: 'Quicklime (Calcium Oxide)',
    formula: 'CaO',
    type: 'Base',
    mnemonic: 'Ca + O',
    breakdown: 'Ca²⁺ (Valency 2) + O²⁻ (Valency 2)',
    trick: 'Valencies cancel out. Adding water to Quicklime makes Slaked Lime.',
  },

  // Gases
  {
    id: 'co2',
    name: 'Carbon Dioxide',
    formula: 'CO₂',
    type: 'Gas',
    mnemonic: '"Di" means two',
    breakdown: 'C (Carbon) + O₂ (Two Oxygens)',
    trick: 'Carbon (C) and Dioxide ("Di" = 2, "oxide" = Oxygen). Therefore CO₂.',
  },
  {
    id: 'nh3',
    name: 'Ammonia',
    formula: 'NH₃',
    type: 'Gas',
    mnemonic: 'Nitrogen + 3 Hydrogens',
    breakdown: 'N (Valency 3) + H (Valency 1)',
    trick: 'Cross-valency: Nitrogen has a valency of 3, Hydrogen is 1. Nitrogen gives 3 to H ➔ NH₃.',
  },
  {
    id: 'so2',
    name: 'Sulfur Dioxide',
    formula: 'SO₂',
    type: 'Gas',
    mnemonic: 'Sulfur + 2 Oxygens',
    breakdown: 'S (Sulfur) + O₂ (Two Oxygens)',
    trick: 'Just like Carbon Dioxide. "Di" means 2, so two oxygens.',
  },
  {
    id: 'o3',
    name: 'Ozone',
    formula: 'O₃',
    type: 'Gas',
    mnemonic: '3 Oxygens',
    breakdown: 'O + O + O',
    trick: 'Oxygen gas we breathe is O2. Ozone is its big brother with 3 oxygens.',
  },

  // Organics
  {
    id: 'ch4',
    name: 'Methane',
    formula: 'CH₄',
    type: 'Organic',
    mnemonic: 'Carbon + 4 Hydrogens',
    breakdown: 'C (Valency 4) + H (Valency 1)',
    trick: 'Carbon always needs 4 bonds. It takes 4 hydrogens to satisfy it. Simplest alkane.',
  },
  {
    id: 'c2h6',
    name: 'Ethane',
    formula: 'C₂H₆',
    type: 'Organic',
    mnemonic: 'Eth = 2 Carbons (Alkane)',
    breakdown: 'Formula CnH2n+2',
    trick: 'n=2. 2n+2 = (2*2)+2 = 6. So C2H6.',
  },
  {
    id: 'c2h4',
    name: 'Ethene',
    formula: 'C₂H₄',
    type: 'Organic',
    mnemonic: 'Eth = 2 Carbons (Alkene)',
    breakdown: 'Formula CnH2n',
    trick: 'n=2. 2n = 4. Has a double bond! So C2H4.',
  },
  {
    id: 'c2h2',
    name: 'Ethyne',
    formula: 'C₂H₂',
    type: 'Organic',
    mnemonic: 'Eth = 2 Carbons (Alkyne)',
    breakdown: 'Formula CnH2n-2',
    trick: 'n=2. 2n-2 = 2. Has a triple bond! So C2H2.',
  },
  {
    id: 'c6h12o6',
    name: 'Glucose',
    formula: 'C₆H₁₂O₆',
    type: 'Organic',
    mnemonic: '6-12-6 Rule',
    breakdown: 'Carbon (6) + Hydrogen (12) + Oxygen (6)',
    trick: 'Remember the ratio 1:2:1 for carbohydrates. 6 Carbons, double the Hydrogens (12), 6 Oxygens.',
  },
  {
    id: 'c2h5oh',
    name: 'Ethanol (Alcohol)',
    formula: 'C₂H₅OH',
    type: 'Organic',
    mnemonic: 'Ethane minus H, plus OH',
    breakdown: 'C₂H₅ (Ethyl) + OH (Alcohol group)',
    trick: '"Eth-" means 2 carbons. "-anol" means it has an OH group. Ethyl group is C2H5.',
  },

  // Others/Common
  {
    id: 'h2o',
    name: 'Water',
    formula: 'H₂O',
    type: 'Other',
    mnemonic: '2 Hydrogens, 1 Oxygen',
    breakdown: 'H⁺ (Valency 1) + O²⁻ (Valency 2)',
    trick: 'Cross-valency: Oxygen gives its 2 to Hydrogen. H₂O.',
  },
];
